# Odin language profile tools
# Install with: mise install

[tools]
odin = "dev-2026-01"

# just task to install ols lsp as this is not supported in mise
# will be globally installed
[tasks.install-ols]
run = """
rm -rf /tmp/ols
mkdir -p ~/.local/bin
git clone https://github.com/DanielGavin/ols.git /tmp/ols
cd /tmp/ols
./build.sh
./odinfmt.sh
mv ols ~/.local/bin/
mv odinfmt ~/.local/bin/
rm -rf /tmp/ols
"""
